# Generated by Django 3.0.8 on 2020-07-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20200723_0349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feeback',
            options={'verbose_name': 'Feeback', 'verbose_name_plural': 'Feeback'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'news', 'verbose_name_plural': 'news'},
        ),
        migrations.RenameField(
            model_name='presentation',
            old_name='nom',
            new_name='titre',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('flickr', 'fa-flickr'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('dribble', 'fa-dribbble'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss')], max_length=20, null=True),
        ),
    ]
