# Generated by Django 3.0.8 on 2020-07-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200723_0446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='video',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram'), ('rss', 'fa-rss'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
