# Generated by Django 3.0.8 on 2020-07-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20200723_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='image',
            field=models.ImageField(null=True, upload_to='image/presentation'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('flickr', 'fa-flickr'), ('dribble', 'fa-dribbble'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest'), ('linkedin', 'fa-linkedin-in'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
