# Generated by Django 3.0.8 on 2020-07-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20200723_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trouver_le_velo',
            name='description',
        ),
        migrations.AddField(
            model_name='trouver_le_velo',
            name='titre',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('pinterest', 'fa-pinterest'), ('google-plus', 'fa-google-plus-g'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble'), ('rss', 'fa-rss'), ('flickr', 'fa-flickr'), ('instagram', 'fa-instagram')], max_length=20, null=True),
        ),
    ]
