# Generated by Django 3.0.8 on 2020-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20200723_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('instagram', 'fa-instagram'), ('google-plus', 'fa-google-plus-g'), ('dribble', 'fa-dribbble'), ('rss', 'fa-rss'), ('linkedin', 'fa-linkedin-in'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
    ]
