# Generated by Django 3.0.8 on 2020-07-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20200723_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('google-plus', 'fa-google-plus-g'), ('rss', 'fa-rss'), ('dribble', 'fa-dribbble'), ('pinterest', 'fa-pinterest'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('facebook', 'fa-facebook'), ('linkedin', 'fa-linkedin-in')], max_length=20, null=True),
        ),
    ]
