# Generated by Django 3.0.8 on 2020-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200723_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('flickr', 'fa-flickr'), ('linkedin', 'fa-linkedin-in'), ('pinterest', 'fa-pinterest'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram'), ('dribble', 'fa-dribbble'), ('facebook', 'fa-facebook'), ('google-plus', 'fa-google-plus-g')], max_length=20, null=True),
        ),
    ]
