# Generated by Django 3.0.8 on 2020-07-25 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20200725_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='our_products',
            name='type_product',
        ),
        migrations.AddField(
            model_name='our_products',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Category_product'),
        ),
        migrations.AlterField(
            model_name='category_product',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feeback',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='our_products',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pub',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='icon',
            field=models.CharField(choices=[('linkedin', 'fa-linkedin-in'), ('dribble', 'fa-dribbble'), ('facebook', 'fa-facebook'), ('rss', 'fa-rss'), ('instagram', 'fa-instagram'), ('flickr', 'fa-flickr'), ('google-plus', 'fa-google-plus-g'), ('pinterest', 'fa-pinterest')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trouver_le_velo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
